name = "Innovation Timespace 6"
author = "Kneelawk"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd5b4e335b5ff7b939906d89edee98193fbc064fed0b9f2821a77b705992657a"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
x-packvulcan-acceptable-loaders = ["fabric"]
