name = "Innovation Timespace 6"
author = "Kneelawk"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74ebeba054cd397e534a4c7c526e93cadd510d0c0657bc7d536c887daf1977fc"

[versions]
minecraft = "1.19.2"
quilt = "0.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1"]
x-packvulcan-acceptable-loaders = ["fabric"]
